### ISSUE TITLE
Possibility of inlcuding phrog IDs in vpf-plm output?

### ISSUE THREAD

**Issue by jwilliams648** [kellylab/viral-protein-function-plm#11]
Hi, 

This is more of a question rather than an issue. Is it possible to provide the probabilities of proteins in a query dataset belonging to specific phrog IDs? Or is the limit of a PLM's accuracy restricted to the (super useful) high-level categories your tool currently provides?

**Comment by jwilliams648** [comment]
By phrog IDs, I'm referring to the IDs in column one of the following table

![Screenshot 2024-10-06 at 5 19 18 PM](https://github.com/user-attachments/assets/d7cdbf07-0661-4146-a9af-3433b4bbbb6a)

**Comment by zachflam** [comment]
Unfortunately it is limited, as you may already understand. The PLM model uses all of the families in a broad category to then assign probability of the class as a whole. You can use the HMMs for individual PHROG family probability but it will be limited to the statistical sequence matching.
