### ISSUE TITLE
The result understand question

### ISSUE THREAD

**Issue by wen1112** [kellylab/viral-protein-function-plm#7]
Hi~, I had try this tool for viral protein annotation, but for the results provided, There some probabilities for each category for each protein, but how can I make sure which category predicted would be choose? How can I understand the results? And there is only 9 category & unknow will be provided for now, if will provided more information?
Looking forward to your reply, thank you~

**Comment by zachflam** [comment]
Hi, thank you for using our annotation classifier. We provide probabilities for all categories but the actual assignment is based on thresholds that we set per category based on FDR of 10%. You can find the actual prediction by the model in the  '_predictions.csv' file, which should have one row per protein and a prediction that considers the FDR. Please let me know if you are not seeing that csv.

**Comment by wen1112** [comment]
![image](https://github.com/user-attachments/assets/5c7b43fc-741d-403f-9f8b-af98b99b64b5)
I see this file in your test provided, so the '_predictions.csv' file is the final result? and this predicted function is the max- probabilities in '_probabilities.csv'?

**Comment by wen1112** [comment]
I have another question, my protein file has 109,221 viral protein (32Mb), but when I run it in google colab, it doesn't worked. This work must need GPU and internet when running? Would you know how many resource will like to use for my file? Actually, I  want to run it in Linux, but it doesn't has internet in compute-node, so I want to know if there has some simply way to solve it? Thank you for your respond.

**Comment by wen1112** [comment]
Sorry, but another question, I see the phrog db annotation has category and annot, but there is just category, if there will provide annot information?

**Comment by zachflam** [comment]
Question 1- Yes '_predictions.csv' file is the final result. It is not necessarily the max of the probabilities as the per-category threshold is calibrated to a test dataset. Please see the paper for a description of the thresholding procedure but basically we desired a error bound so we set thresholds with FDR < 10%.

Question 2- That number of proteins will hit the limit for Google colab unfortunately. On a single GPU, ~100000 proteins should take less than 1 hr. The way the code is structured right now it does have to be connected to the internet to download the huggingface protein language model. See #1 

Question 3- our model only uses the category-level annotation as we sought to generalize the annotations to unknown proteins at this level.
