### ISSUE TITLE
The AWS resource need

### ISSUE THREAD

**Issue by wen1112** [kellylab/viral-protein-function-plm#8]
Hi~, I want to run it on AWS, but I need estimate the budgeted cost of data analysis for this task, but I don't know how much resource this task need, my protein file has 109,220 viral protein (38.9Mb), could you help me? Thank you for your support.

**Comment by zachflam** [comment]
I am not sure that I can say what the exact resource requirements will be. But based on my experience running the code on an instance with 2 GPUs, it would take ~3 hrs. The sequence embedding procedure takes ~10-15s/100 sequences.

**Comment by wen1112** [comment]
Thank you so much, would you know 1 CPU could adress how many protein virus?

**Comment by wen1112** [comment]
another，How much Memory would be used for this project? if there has a data for it

**Comment by zachflam** [comment]
The memory is just to store the protein language model, which is ~1.75Gb.
On a CPU, the process will take a very long time unfortunately. I do not know how to assess how long.
